In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel("/content/indian-job-market-dataset-2025.xlsx")

**DATA CLEANING**

In [ ]:
df.head()
df.shape

(97929, 17)

In [ ]:
df.columns

Index(['title', 'jobId', 'currency', 'jobUploaded', 'companyName',
       'tagsAndSkills', 'experience', 'salary', 'location', 'companyId',
       'ReviewsCount', 'AggregateRating', 'jobDescription', 'minimumSalary',
       'maximumSalary', 'minimumExperience', 'maximumExperience'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  object
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  object
 3   jobUploaded        97929 non-null  object
 4   companyName        97925 non-null  object
 5   tagsAndSkills      97358 non-null  object
 6   experience         95824 non-null  object
 7   salary             97929 non-null  object
 8   location           97929 non-null  object
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  object
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 12.7+ MB

In [ ]:
df.isnull().sum()

title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

In [ ]:
df["jobId"].duplicated().sum()

np.int64(250)

In [ ]:
df["jobId"].nunique()

97679

In [ ]:
df.duplicated().sum()

np.int64(247)

In [ ]:
dup_rows = df[df["jobId"].duplicated(keep=False)]

dup_rows.groupby("jobId").nunique().max(axis=1).sort_values(ascending=False).head()

jobId
11025022950    2
11025020549    2
31025020550    2
11025010305    1
11025014967    1
dtype: int64

In [ ]:
suspicious_ids = [11025022950, 11025020549, 31025020550]

df[df["jobId"].isin(suspicious_ids)]

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
15261,Bancassurance Manager,11025020549,INR,2 Days Ago,Amrit Consultancy,"Health Insurance Sales,Banca,Bancassurance,Ins...",0-5 Yrs,1-4.25 Lacs PA,"Noida, Gurugram, Delhi / NCR",4803914,NaN,NaN,Candidate should be from the insurance industr...,100000.0,425000.0,0.0,5.0
44893,N8N end To end developer,31025020550,INR,Just Now,Confidential,"Integration,Rest,API,English,Telugu,Api Gatewa...",2-4 Yrs,1.2-1.44 Lacs PA,Parchur,125142239,NaN,NaN,<p> </p><p> <strong>Project Leadership</strong...,120000.0,144000.0,2.0,4.0
53987,N8N end To end developer,31025020550,INR,Just Now,Confidential,"Integration,Rest,API,English,Telugu,Api Gatewa...",2-4 Yrs,1.2-3.6 Lacs PA,Chirala,125142239,NaN,NaN,<br /><p><strong>Workflow Development</strong>...,120000.0,360000.0,2.0,4.0
56106,Agency / Bancassurance Manager Life / Health I...,11025020549,INR,2 Days Ago,Amrit Consultancy,"Health Insurance Sales,Banca,Bancassurance,Ins...",1-6 Yrs,2.25-7.25 Lacs PA,"Noida, Mau, Prayagraj, Varanasi, Chandigarh, M...",4803914,NaN,NaN,Candidate should be from the insurance industr...,225000.0,725000.0,1.0,6.0
77489,Senior Devops Engineer,11025022950,INR,2 Days Ago,Optum,"Terraform,Ansible,Kubernetes,Senior,Devops",6-11 Yrs,Not disclosed,Hybrid - Bengaluru,124550882,7175.0,4.0,<p> </p><p>design and code integrated piplelin...,0.0,0.0,6.0,11.0
87707,Senior Devops Engineer,11025022950,INR,2 Days Ago,Optum,"Terraform,Ansible,Kubernetes,Senior,Devops",6-11 Yrs,Not disclosed,Hybrid - Bengaluru,124550882,7174.0,4.0,<p> </p><p>design and code integrated piplelin...,0.0,0.0,6.0,11.0

In [ ]:
for job_id in suspicious_ids:
    rows = df[df["jobId"] == job_id]

    print("\nJOB ID:", job_id)

    for column in df.columns:
        if rows[column].nunique(dropna=False) > 1:
            print(column, "->", rows[column].tolist())

JOB ID: 11025022950
ReviewsCount -> [7175.0, 7174.0]

JOB ID: 11025020549
title -> ['Bancassurance Manager', 'Agency / Bancassurance Manager Life / Health Insurance']
tagsAndSkills -> ['Health Insurance Sales,Banca,Bancassurance,Insurance Sales,Bancassurance Sales,Insurance,Management,Health', 'Health Insurance Sales,Banca,Bancassurance,Insurance Sales,Bancassurance Sales,Banking And Insurance,Agency Channel,Life Insurance']
experience -> ['0-5 Yrs', '1-6 Yrs']
salary -> ['1-4.25 Lacs PA', '2.25-7.25 Lacs PA']
location -> ['Noida, Gurugram, Delhi / NCR', 'Noida, Mau, Prayagraj, Varanasi, Chandigarh, Meerut, Faridabad, Gurugram, Delhi / NCR']
minimumSalary -> [100000.0, 225000.0]
maximumSalary -> [425000.0, 725000.0]
minimumExperience -> [0.0, 1.0]
maximumExperience -> [5.0, 6.0]

JOB ID: 31025020550
salary -> ['1.2-1.44 Lacs PA', '1.2-3.6 Lacs PA']
location -> ['Parchur', 'Chirala']
jobDescription -> ['<p> </p><p> <strong>Project Leadership</strong></p><ul><li>Lead <strong>end-to-end automation projects</strong> using n8n (from requirement gathering to production deployment).<br /> </li><li>Collaborate with <strong>business stakeholders, QA, and DevOps</strong> teams to deliver automation solutions</li></ul>\n\nAnnual bonus\nFood allowance', '<br /><p><strong>Workflow Development</strong></p><ul><li>Design, build, and optimize <strong>complex workflows</strong> in n8n.<br /> </li><li>Create <strong>custom n8n nodes</strong> in JavaScript/TypeScript when required.<br /> </li><li>Handle <strong>multi-step workflows</strong>, error handling, retries, and scalability.<br /></li></ul>\n\nAnnual bonus\nFood allowance']
maximumSalary -> [144000.0, 360000.0]

In [ ]:
df_clean = df.drop_duplicates()

In [ ]:
df_clean.shape

(97682, 17)

In [ ]:
missing_571 = df_clean[
    df_clean["tagsAndSkills"].isnull() &
    df_clean["minimumSalary"].isnull() &
    df_clean["maximumSalary"].isnull() &
    df_clean["minimumExperience"].isnull() &
    df_clean["maximumExperience"].isnull()
]

missing_571.shape

(571, 17)

In [ ]:
missing_571[["title", "companyName", "location", "jobDescription"]].head(10)

,title,companyName,location,jobDescription
240,Product Designer Intern,Greedygame,Bengaluru,<div> Location: Bangalore (Hybrid) | Experienc...
241,Intern,Valeo,Chennai,Willingness to work in laboratory shifts opera...
363,Trainee - Survey Research,Nexdigm (SKP),Bengaluru,. Must be comfortable traveling extensively a...
418,HR Intern,Unique,Chennai,"<p>1. Work on designing, updating descriptions..."
432,driven Professional,Vaibhav Global,Jaipur,. Desired Qualifications & Key Competencies: ...
435,Trainee - Market Research,Nexdigm (SKP),Bengaluru,. Additional Requirement: . Must be comforta...
436,Trainee - Market Research,Nexdigm (SKP),Bengaluru,Nexdigm (SKP) is looking for Trainee - Market ...
613,Marketing Artist- Mobile Games,Nukebox Studios,Bengaluru(Lalbagh Road),Experience: 0-1 Year. Company: Nukebox Studios...
734,Internship,Deyor Camps,Gurugram,Deyor Camps is looking for Internship to joi...
735,Marketing ( Intern ),Lighthouse Info Systems,Nagpur,Lighthouse Info Systems Pvt. Ltd. is looking ...

In [ ]:
df_clean[df_clean["ReviewsCount"].isnull()][
    ["companyName", "ReviewsCount", "AggregateRating"]
].head(10)

                     companyName  ReviewsCount  AggregateRating
0                          Orion           NaN              NaN
3            GNR Global Services           NaN              NaN
5             Vedaant Techno Art           NaN              NaN
10           GNR Global Services           NaN              NaN
12           GNR Global Services           NaN              NaN
15  Manpowergroup Services India           NaN              NaN
17          ALP Talent Solutions           NaN              NaN
18          ALP Talent Solutions           NaN              NaN
19          ALP Talent Solutions           NaN              NaN
24         Human Before Resource           NaN              NaN

In [ ]:
df_clean[df_clean["companyName"].isnull()]

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
13759,Manager - JDE Project Manager,31025006802,INR,Today,NaN,"Jd Edwards Enterpriseone,ERP Implementation,JD...",10-16 Yrs,Not disclosed,Ahmedabad,1346914,460.0,3.9,Must have hands on experience on JD Edwards ER...,0.0,0.0,10.0,16.0
47177,Manager - Activation,300925010754,INR,3 Days Ago,NaN,"Brand Activation,Activation,Btl Activation,Roa...",6-11 Yrs,Not disclosed,Gurugram,1346914,460.0,3.9,Willingness to travel extensively as per activ...,0.0,0.0,6.0,11.0
49921,3D Designer (Event 3D Work Experience Required),270925004556,INR,6 Days Ago,NaN,"Sketchup,3ds Max,3D Model,3D Designing,3D Mode...",10-18 Yrs,Not disclosed,Gurugram,1346914,460.0,3.9,Requirements: . 8 10 years of experience in 3...,0.0,0.0,10.0,18.0
66924,2D Designer,250925034601,INR,8 Days Ago,NaN,"2D design,2D Animation,Photoshop,Graphic Desig...",8-13 Yrs,8-12 Lacs PA,Gurugram,1346914,460.0,3.9,Required Skills and Experience: . Bachelors d...,800000.0,1200000.0,8.0,13.0

In [ ]:
(df_clean["minimumSalary"] > df_clean["maximumSalary"]).sum()

np.int64(0)

In [ ]:
(df_clean["minimumExperience"] > df_clean["maximumExperience"]).sum()

np.int64(0)

In [ ]:
df_clean[["minimumSalary", "maximumSalary"]].describe()

       minimumSalary  maximumSalary
count   9.711100e+04   9.711100e+04
mean    1.983259e+05   3.186440e+05
std     5.643068e+05   8.421283e+05
min     0.000000e+00   0.000000e+00
25%     0.000000e+00   0.000000e+00
50%     0.000000e+00   0.000000e+00
75%     2.000000e+05   3.750000e+05
max     7.000000e+07   9.500000e+07

In [ ]:
(df_clean["minimumSalary"] == 0).sum()

np.int64(63973)

In [ ]:
(df_clean["maximumSalary"] == 0).sum()

np.int64(63965)

In [ ]:
df_clean[df_clean["maximumSalary"] > 5000000][
    ["title", "companyName", "salary", "minimumSalary", "maximumSalary"]
].sort_values("maximumSalary", ascending=False).head(10)

,title,companyName,salary,minimumSalary,maximumSalary
89340,Deputy Manager,Bombay Coated And Special Steels,7-9.5 Cr PA,70000000.0,95000000.0
4048,Senior Director AI ML,Employers4employees,2-3 Cr PA,20000000.0,30000000.0
4115,Chartered Accountant,European Company,2-3 Cr PA,20000000.0,30000000.0
64394,Chief Executive Officer - API / Pharma (Tamil ...,B2N Management Consulting Kerala,1.75-3 Cr PA,17500000.0,30000000.0
42231,Openings For Director (Physical design)at Hyde...,Cambio Consulting,1-3 Cr PA,10000000.0,30000000.0
6226,Director Manufacturing Operations,Sampark Career Developers,1-2 Cr PA,10000000.0,20000000.0
7160,Urgent Requirement Medical Oncologist Doctors,Tech India,90 Lacs-1.5 Cr PA,9000000.0,15000000.0
4154,"COO, Rural Startup Co, Hybrid , Consulting + S...",Executive Tracks Associates,75 Lacs-1.5 Cr PA,7500000.0,15000000.0
7610,AVP/VP- HR,Tmangoes Hr Consulting,70 Lacs-1.5 Cr PA,7000000.0,15000000.0
49305,Head Project Planning & Control,Genxhire Services,70 Lacs-1.5 Cr PA,7000000.0,15000000.0

In [ ]:
df_clean[
    (df_clean["minimumSalary"] == 0) &
    (df_clean["maximumSalary"] != 0)
][
    ["title", "companyName", "salary", "minimumSalary", "maximumSalary"]
]

,title,companyName,salary,minimumSalary,maximumSalary
8676,Sales Manager,Inframart Realtech India,0-1.08 Cr PA,0.0,10800000.0
46735,Housekeeping Associate,Somanda Vineyards And Resort,0-1.8 Lacs PA,0.0,180000.0
51893,Engineer,Madhav Copper,0-2.4 Lacs PA,0.0,240000.0
57935,Digital Marketing Executive,Enthusionz Digital,"0-1,000 PA",0.0,1000.0
63417,Sales Manager,AHN Hotel And Management Services,"0-1,000 PA",0.0,1000.0
65641,Accounting Assistant Manager,Virtuoso Professional Services Llp,"0-1,000 PA",0.0,1000.0
65681,Senior Accountant,Oval Projects Engineering Limited,"0-1,000 PA",0.0,1000.0
67070,Senior Recruiter,Ramsol,0-5 Lacs PA,0.0,500000.0

In [ ]:
df_clean["minSalary_clean"] = df_clean["minimumSalary"]
df_clean["maxSalary_clean"] = df_clean["maximumSalary"]

/tmp/ipykernel_4739/3174359798.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["minSalary_clean"] = df_clean["minimumSalary"]
/tmp/ipykernel_4739/3174359798.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["maxSalary_clean"] = df_clean["maximumSalary"]

In [ ]:
df_clean.loc[df_clean["minSalary_clean"] == 0, "minSalary_clean"] = np.nan
df_clean.loc[df_clean["maxSalary_clean"] == 0, "maxSalary_clean"] = np.nan

In [ ]:
df_clean = df.drop_duplicates().copy()

In [ ]:
df_clean["minSalary_clean"] = df_clean["minimumSalary"]
df_clean["maxSalary_clean"] = df_clean["maximumSalary"]

In [ ]:
df_clean.loc[df_clean["minSalary_clean"] == 0, "minSalary_clean"] = np.nan
df_clean.loc[df_clean["maxSalary_clean"] == 0, "maxSalary_clean"] = np.nan

In [ ]:
df_clean[["minimumSalary", "minSalary_clean",
          "maximumSalary", "maxSalary_clean"]].head(10)

   minimumSalary  minSalary_clean  maximumSalary  maxSalary_clean
0       200000.0         200000.0       400000.0         400000.0
1       300000.0         300000.0       500000.0         500000.0
2            0.0              NaN            0.0              NaN
3        70000.0          70000.0       200000.0         200000.0
4       800000.0         800000.0      1800000.0        1800000.0
5       350000.0         350000.0       600000.0         600000.0
6            0.0              NaN            0.0              NaN
7            0.0              NaN            0.0              NaN
8            0.0              NaN            0.0              NaN
9            0.0              NaN            0.0              NaN

In [ ]:
(df_clean["minimumExperience"] == 0).sum()

np.int64(12363)

In [ ]:
(df_clean["maximumExperience"] == 0).sum()

np.int64(532)

In [ ]:
df_clean[
    (df_clean["minimumExperience"] == 0) &
    (df_clean["maximumExperience"] == 0)
][
    ["title", "experience", "jobDescription",
     "minimumExperience", "maximumExperience"]
].head(20)

,title,experience,jobDescription,minimumExperience,maximumExperience
263,Internal Audit - Consultant (Contractual Posit...,0 Yrs,Fresher CA with minimum 0-1 years of post-qual...,0.0,0.0
264,"Software Engineer/Business Analyst, 2025 gradu...",0 Yrs,Designation: Trainee . Educational Background:...,0.0,0.0
389,Chartered Accountant Trainee,0 Yrs,"Qualified CA (Fresher),Hardworking,Sincere and...",0.0,0.0
391,PD Lab Apprentice,0 Yrs,Maintain laboratory equipment and ensure adher...,0.0,0.0
448,Python Software Developer,0 Yrs,We are hiring for a front-end developer\nLocat...,0.0,0.0
449,Sap Sd Consultant,0 Yrs,We are hiring for an SAP SD consultant \nLocat...,0.0,0.0
481,CX Associate,0 Yrs,Job Overview: . We are looking for a passiona...,0.0,0.0
493,Human Resource Intern,0 Yrs,<p><strong>Job title : </strong>HR Intern</p><...,0.0,0.0
515,IT Sales / Marketing,0 Yrs,"Bachelors degree in Business Administration,Ma...",0.0,0.0
532,Account Executive,0 Yrs,<p>Responsibilities:</p><ul><li>Manage account...,0.0,0.0
638,Medical Billing Non Voice Process (Night Shift...,NaN,Willing to work in Night Shift <br><br> We are...,0.0,0.0
813,Openings For Process Executive!!!,0 Yrs,Day shift - Female & Male Candidates <br><br>N...,0.0,0.0
828,Legal Executive,0 Yrs,Custody of original contracts must be maintain...,0.0,0.0
839,Opening For a Fresher,0 Yrs,<p><strong>Role & responsibilities</strong> </...,0.0,0.0
865,Sales Officer - GT - Kolhapur,0 Yrs,"About Zydus Wellness\n\n Zydus Wellness, ...",0.0,0.0
917,Openings For Financial Associate role- Fresher...,NaN,"Willing to work in any assigned shift (day,nig...",0.0,0.0
948,Sr. Relationship Manager / Wealth Manager,0 Yrs,Maximum age limit 35 years. <br><br> Good Expe...,0.0,0.0
963,Business Development Manager,0 Yrs,<p><strong>Role & responsibilities</strong> </...,0.0,0.0
967,SAP Fresher - Chennai,0 Yrs,<p> Please share your CV's to <u><strong>rezon...,0.0,0.0
968,Fresher Opening- Life Science - HR Recruiter -...,NaN,<p> Hi All... </p><br /><p>Hope you all are do...,0.0,0.0

In [ ]:
(df_clean["minimumExperience"] == 0).sum(), (df_clean["maximumExperience"] == 0).sum()

(np.int64(12363), np.int64(532))

In [ ]:
(
    (df_clean["minimumExperience"] == 0) &
    (df_clean["maximumExperience"] == 0)
).sum()

np.int64(532)

In [ ]:
df_clean["tagsAndSkills"].isnull().sum()

np.int64(571)

In [ ]:
df_clean["tagsAndSkills"].head(10)

0    Communication,Manpower,Staffing,Convincing Pow...
1    Safety Officer Activities,Fire Protection,Fire...
2    Performance Marketing,User Acquisition,growth ...
3    Fluent English,Spoken English,Good English Com...
4    Product Marketing,CNS,Product Management,Nephr...
5    Tds Filing,ITR,Gst Filing,Balance Sheet Finali...
6    Booth,Conveyor,Special Process,Utility Mainten...
7    M.S Office,SAP,Computer Skills,MS Office,Techn...
8     SAP,Laboratory Knowledge,Microsoft,Technical,Lab
9    Sre,Azure Devops,Monitoring Tools,Site,Site Re...
Name: tagsAndSkills, dtype: object

In [ ]:
df_clean["tagsAndSkills"].dropna().str.lower().head(10)

0    communication,manpower,staffing,convincing pow...
1    safety officer activities,fire protection,fire...
2    performance marketing,user acquisition,growth ...
3    fluent english,spoken english,good english com...
4    product marketing,cns,product management,nephr...
5    tds filing,itr,gst filing,balance sheet finali...
6    booth,conveyor,special process,utility mainten...
7    m.s office,sap,computer skills,ms office,techn...
8     sap,laboratory knowledge,microsoft,technical,lab
9    sre,azure devops,monitoring tools,site,site re...
Name: tagsAndSkills, dtype: object

In [ ]:
df_clean["skills_clean"] = df_clean["tagsAndSkills"].str.lower()

In [ ]:
df_clean["skills_clean"] = df_clean["skills_clean"].str.replace(" ", "", regex=False)

In [ ]:
df_clean["skills_clean"] = df_clean["tagsAndSkills"].str.lower()

In [ ]:
df_clean["skills_clean"].head(10)

0    communication,manpower,staffing,convincing pow...
1    safety officer activities,fire protection,fire...
2    performance marketing,user acquisition,growth ...
3    fluent english,spoken english,good english com...
4    product marketing,cns,product management,nephr...
5    tds filing,itr,gst filing,balance sheet finali...
6    booth,conveyor,special process,utility mainten...
7    m.s office,sap,computer skills,ms office,techn...
8     sap,laboratory knowledge,microsoft,technical,lab
9    sre,azure devops,monitoring tools,site,site re...
Name: skills_clean, dtype: object

In [ ]:
skills_list = df_clean["skills_clean"].dropna().str.split(",")

In [ ]:
skills_list.head()

0    [communication, manpower, staffing, convincing...
1    [safety officer activities, fire protection, f...
2    [performance marketing, user acquisition, grow...
3    [fluent english, spoken english, good english ...
4    [product marketing, cns, product management, n...
Name: skills_clean, dtype: object

In [ ]:
all_skills = skills_list.explode()

In [ ]:
all_skills.head(20)

0                communication
0                     manpower
0                     staffing
0             convincing power
0                       hiring
0                  recruitment
0                           sr
0         communication skills
1    safety officer activities
1              fire protection
1                  fire safety
1             fire engineering
1              fire prevention
1            safety management
1              fire management
1              hazard analysis
2        performance marketing
2             user acquisition
2             growth marketing
2               paid marketing
Name: skills_clean, dtype: object

In [ ]:
skill_counts = all_skills.value_counts()

In [ ]:
skill_counts.head(20)

skills_clean
sales                   9206
python                  5846
project management      5541
customer service        5122
sap                     5043
management              4849
css                     4188
java                    4088
sql                     3982
business development    3745
communication skills    3499
development             3311
javascript              3006
c#                      2978
marketing               2503
troubleshooting         2470
agile                   2459
accounting              2435
english                 2273
automation              2269
Name: count, dtype: int64

In [ ]:
skill_counts.head(50)

skills_clean
sales                      9206
python                     5846
project management         5541
customer service           5122
sap                        5043
management                 4849
css                        4188
java                       4088
sql                        3982
business development       3745
communication skills       3499
development                3311
javascript                 3006
c#                         2978
marketing                  2503
troubleshooting            2470
agile                      2459
accounting                 2435
english                    2273
automation                 2269
team management            2268
analytical                 2159
oracle                     2135
networking                 2085
rest                       2055
operations                 2043
software testing           1993
c++                        1987
aws                        1884
data analysis              1870
training                   1850
voice process              1844
customer support           1828
lead generation            1800
recruitment                1797
bpo                        1768
continuous integration     1751
consulting                 1729
html                       1600
software development       1579
application development    1574
microservices              1544
b2b sales                  1536
kubernetes                 1510
spring boot                1499
web services               1468
finance                    1460
erp                        1453
channel sales              1398
excel                      1312
Name: count, dtype: int64

In [ ]:
tech_keywords = [
    "software",
    "developer",
    "engineer",
    "data",
    "machine learning",
    "ml",
    "artificial intelligence",
    "ai",
    "analyst",
    "devops",
    "cloud",
    "cyber",
    "programmer",
    "technical"
]

pattern = "|".join(tech_keywords)

tech_jobs = df_clean[
    df_clean["title"].str.contains(pattern, case=False, na=False)
].copy()

In [ ]:
tech_jobs.shape

(36005, 20)

In [ ]:
tech_skills = tech_jobs["skills_clean"].dropna().str.split(",").explode()

In [ ]:
tech_skill_counts = tech_skills.value_counts()

In [ ]:
tech_skill_counts.head(30)

skills_clean
python                     4638
css                        3343
java                       3092
sql                        3074
javascript                 2325
development                2212
c#                         1998
sap                        1846
project management         1823
aws                        1528
troubleshooting            1520
rest                       1494
agile                      1438
c++                        1399
automation                 1398
continuous integration     1309
software development       1290
application development    1279
spring boot                1245
oracle                     1233
microservices              1222
html                       1199
kubernetes                 1175
software testing           1133
web services               1118
react.js                   1080
data analysis              1041
networking                 1035
machine learning           1022
sales                       992
Name: count, dtype: int64

In [ ]:
ai_ml_keywords = [
    "artificial intelligence",
    "machine learning",
    "machine learning engineer",
    "ml engineer",
    "ai engineer",
    "ai developer",
    "ml developer",
    "data scientist",
    "deep learning",
    "nlp",
    "computer vision"
]

pattern_ai_ml = "|".join(ai_ml_keywords)

ai_ml_jobs = df_clean[
    df_clean["title"].str.contains(pattern_ai_ml, case=False, na=False)
].copy()

In [ ]:
ai_ml_jobs.shape

(955, 20)

In [ ]:
ai_ml_skills = ai_ml_jobs["skills_clean"].dropna().str.split(",").explode()

In [ ]:
ai_ml_skill_counts = ai_ml_skills.value_counts()

In [ ]:
ai_ml_skill_counts.head(30)

skills_clean
python                         543
machine learning               523
artificial intelligence        307
natural language processing    256
tensorflow                     206
image processing               158
pytorch                        155
deep learning                  148
data science                   146
chatbot                        139
algorithms                     126
generative ai                  113
sql                             99
ml                              89
data                            77
data analysis                   76
machine                         75
gcp                             74
aws                             72
kubernetes                      71
scikit-learn                    63
machine learning algorithms     62
aiml                            59
computer science                58
llm                             57
computer vision                 55
deep learning frameworks        49
c++                             47
statistics                      46
data analytics                  42
Name: count, dtype: int64

In [ ]:
ai_ml_skill_counts.head(50)

skills_clean
python                         543
machine learning               523
artificial intelligence        307
natural language processing    256
tensorflow                     206
image processing               158
pytorch                        155
deep learning                  148
data science                   146
chatbot                        139
algorithms                     126
generative ai                  113
sql                             99
ml                              89
data                            77
data analysis                   76
machine                         75
gcp                             74
aws                             72
kubernetes                      71
scikit-learn                    63
machine learning algorithms     62
aiml                            59
computer science                58
llm                             57
computer vision                 55
deep learning frameworks        49
c++                             47
statistics                      46
data analytics                  42
microsoft azure                 40
langchain                       37
keras                           36
neural networks                 35
intelligence                    34
development                     33
data munging                    31
analytical                      30
agentic ai                      30
automation                      30
continuous integration          28
hive                            28
gen ai                          28
tableau                         28
open source                     27
cloud                           27
gen                             25
nlp                             25
monitoring                      24
data structures                 24
Name: count, dtype: int64

In [ ]:
skill_mapping = {
    "ml": "machine learning",
    "machine learning algorithms": "machine learning",
    "nlp": "natural language processing",
    "gen ai": "generative ai"
}

In [ ]:
all_skills_normalized = all_skills.replace(skill_mapping)

In [ ]:
all_skills_normalized.value_counts().head(30)

skills_clean
sales                   9206
python                  5846
project management      5541
customer service        5122
sap                     5043
management              4849
css                     4188
java                    4088
sql                     3982
business development    3745
communication skills    3499
development             3311
javascript              3006
c#                      2978
marketing               2503
troubleshooting         2470
agile                   2459
accounting              2435
english                 2273
automation              2269
team management         2268
analytical              2159
oracle                  2135
networking              2085
rest                    2055
operations              2043
software testing        1993
c++                     1987
aws                     1884
data analysis           1870
Name: count, dtype: int64

In [ ]:
all_skills_normalized.value_counts().loc[
    ["machine learning",
     "natural language processing",
     "generative ai"]
]

skills_clean
machine learning               1458
natural language processing     514
generative ai                   255
Name: count, dtype: int64

In [ ]:
all_skills_normalized[
    all_skills_normalized.str.strip() != all_skills_normalized
].head(20)

1134                         iti motor mechanic
4393                              truck driving
5000                                      tutor
5585                             car technician
5585                               car mechanic
6529               strong knowledge of ms office
6529                               us healthcare
6529                                typing speed
6529                     life science background
6617                                    dot net
10287                            car technician
10413                            car technician
10423                               call centre
13357                         holter monitoring
15050                              adaptability
15050                  basic computer knowledge
15050                             voice clarity
15074                              goal setting
17975    authorised service centre coordination
18905                            car technician
Name: skills_clean, dtype: object

In [ ]:
all_skills_normalized = all_skills_normalized.str.strip()

In [ ]:
all_skills_normalized[
    all_skills_normalized.str.strip() != all_skills_normalized
].head()

Series([], Name: skills_clean, dtype: object)

In [ ]:
all_skills_normalized.value_counts().loc[
    ["machine learning",
     "natural language processing",
     "generative ai"]
]

skills_clean
machine learning               1459
natural language processing     514
generative ai                   255
Name: count, dtype: int64

In [ ]:
tech_skill_counts = tech_jobs["skills_clean"].value_counts()

tech_skill_counts.head(20)

skills_clean
sap abap,odata,sap fica,adobe forms,smart forms,collections,invoicing,sap s/4hana                                                42
er studio,data modeling,erwin,aws,sql,nosql,gcp,data architecture                                                                37
scala,hadoop,spark,python,airflow,jenkins,hive,github                                                                            29
airflow,jenkins,scala,hadoop,python,pyspark,hive,linux                                                                           29
airflow,scala,cicd,spark,python,jenkins,pyspark,test                                                                             29
application design,sap abap development,design principles,sap hana,sap abap,rest,css,sap                                         29
medical coding,hcpcs,clinical research,cpt,medical transcription,cpc,icd,cpt coding                                              29
python,scala,hadoop,data modeling,etl,unix,apis,sql                                                                              29
scala,hadoop,big data engineer,spark,aws,data,big data                                                                           26
investment banking,capital market,derivatives,investment banking operations,fixed income,settlements,trading,data management     26
scala,hadoop,big data engineer,spark,aws,big data,data                                                                           25
java,spring boot,react.js,angular,microservices,sql,full stack,development                                                       21
kyc,aml,risk management,risk assessment,cdd,due diligence,anti money laundering,documentation                                    18
machine learning,tableau,machine learning algorithms,statistics,data munging,image processing,algorithms,chatbot                 17
application design,sap abap development,design principles,sap hana,sap abap,c#,rest,css                                          17
bpo,quality analysis,call monitoring,quality monitoring,qc tools,call audit,feedback,excellent communication in english          17
training,interpersonal skills,team management,irda,induction training,bancassurance,training and development,management          16
fabrication,reactors,tanks,asme,radiography testing,ultrasonic testing,heat exchangers,pressure vessels code                     16
gcp,cicd,devops,python,kubernetes,terraform,cka,sql                                                                              15
natural language processing,deployment process,artificial intelligence,tensorflow,pytorch,image processing,chatbot,kubernetes    15
Name: count, dtype: int64

In [ ]:
tech_skill_counts = tech_jobs["skills_clean"].explode().value_counts()

tech_skill_counts.head(30)

skills_clean
sap abap,odata,sap fica,adobe forms,smart forms,collections,invoicing,sap s/4hana                                                42
er studio,data modeling,erwin,aws,sql,nosql,gcp,data architecture                                                                37
scala,hadoop,spark,python,airflow,jenkins,hive,github                                                                            29
airflow,jenkins,scala,hadoop,python,pyspark,hive,linux                                                                           29
airflow,scala,cicd,spark,python,jenkins,pyspark,test                                                                             29
application design,sap abap development,design principles,sap hana,sap abap,rest,css,sap                                         29
medical coding,hcpcs,clinical research,cpt,medical transcription,cpc,icd,cpt coding                                              29
python,scala,hadoop,data modeling,etl,unix,apis,sql                                                                              29
scala,hadoop,big data engineer,spark,aws,data,big data                                                                           26
investment banking,capital market,derivatives,investment banking operations,fixed income,settlements,trading,data management     26
scala,hadoop,big data engineer,spark,aws,big data,data                                                                           25
java,spring boot,react.js,angular,microservices,sql,full stack,development                                                       21
kyc,aml,risk management,risk assessment,cdd,due diligence,anti money laundering,documentation                                    18
machine learning,tableau,machine learning algorithms,statistics,data munging,image processing,algorithms,chatbot                 17
application design,sap abap development,design principles,sap hana,sap abap,c#,rest,css                                          17
bpo,quality analysis,call monitoring,quality monitoring,qc tools,call audit,feedback,excellent communication in english          17
training,interpersonal skills,team management,irda,induction training,bancassurance,training and development,management          16
fabrication,reactors,tanks,asme,radiography testing,ultrasonic testing,heat exchangers,pressure vessels code                     16
gcp,cicd,devops,python,kubernetes,terraform,cka,sql                                                                              15
natural language processing,deployment process,artificial intelligence,tensorflow,pytorch,image processing,chatbot,kubernetes    15
sales,marketing,relationship management,lead generation,selling,channel sales,retail sales,sales process                         15
debugging,sap,development methodologies,application development,troubleshooting,css,web services,jsp                             14
hive,python,machine learning,tensorflow,keras,time series analysis,algorithms,data analysis                                      14
jenkins,docker,gcp,devops tools,kubernetes,gke cluster,github,shell scripting                                                    14
java,maven,oracle,microservices,jenkins,git,postgresql,devops tools                                                              14
sales,cement sales,paint sales,furniture sales,channel sales,construction material,b2b sales,building material sales             14
airflow,sql,unix linux,scala,python,pyspark,java,github                                                                          14
cicd methodology,scala,data flow,spark,jenkins,data engineering,cloud data flow,bigquery                                         14
gcp,spark,scala,hadoop,airflow,jenkins,hive,bigquery                                                                             14
data engineering,bigquery,sql queries,etl,sql,etl pipelines,java,gcp                                                             14
Name: count, dtype: int64

In [ ]:
tech_skills = (
    tech_jobs["skills_clean"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

tech_skill_counts = tech_skills.value_counts()

tech_skill_counts.head(30)

skills_clean
python                     4638
css                        3343
java                       3092
sql                        3075
javascript                 2325
development                2212
c#                         1998
sap                        1846
project management         1824
aws                        1528
troubleshooting            1520
rest                       1494
agile                      1438
c++                        1399
automation                 1398
continuous integration     1309
software development       1290
application development    1279
spring boot                1245
oracle                     1233
microservices              1222
html                       1199
kubernetes                 1175
software testing           1133
web services               1118
react.js                   1080
data analysis              1041
networking                 1035
machine learning           1023
sales                       992
Name: count, dtype: int64

In [ ]:
ai_ml_keywords = [
    "artificial intelligence",
    "machine learning",
    "machine learning engineer",
    "ml engineer",
    "ai engineer",
    "ai developer",
    "ml developer",
    "data scientist",
    "deep learning",
    "nlp",
    "computer vision"
]

pattern_ai_ml = "|".join(ai_ml_keywords)

ai_ml_jobs = df_clean[
    df_clean["title"].str.contains(
        pattern_ai_ml,
        case=False,
        na=False
    )
].copy()

In [ ]:
ai_ml_jobs.shape

(955, 20)

In [ ]:
ai_ml_jobs["skills_clean"]

223      data science,nlp,machine learning,opencv,artif...
251                                         data scientist
748                                                    NaN
1224     aiml,artificial intelligence,machine learning,...
1244     artificial intelligence,machine learning,pytor...
                               ...
97474    generative ai,machine learning,python,analytic...
97579    data cleansing,devops,python,machine learning,...
97654    mlops,azure,docker,gcp,ci/cd,mlflow,aws,kubern...
97781    generative ai,python,data science,pytorch,arti...
97811    cloud platforms,artificial intelligence,python...
Name: skills_clean, Length: 955, dtype: object

In [ ]:
ai_skills = (
    ai_ml_jobs["skills_clean"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

ai_skill_counts = ai_skills.value_counts()

ai_skill_counts.head(30)

skills_clean
python                         543
machine learning               523
artificial intelligence        307
natural language processing    256
tensorflow                     206
image processing               158
pytorch                        155
deep learning                  148
data science                   146
chatbot                        139
algorithms                     126
generative ai                  113
sql                             99
ml                              89
data                            77
data analysis                   76
machine                         75
gcp                             74
aws                             72
kubernetes                      71
scikit-learn                    63
machine learning algorithms     62
aiml                            59
computer science                58
llm                             57
computer vision                 55
deep learning frameworks        49
c++                             47
statistics                      46
data analytics                  42
Name: count, dtype: int64

In [ ]:
ai_skill_percentage = (ai_skill_counts / len(ai_ml_jobs) * 100).round(2)

ai_skill_percentage.head(30)

skills_clean
python                         56.86
machine learning               54.76
artificial intelligence        32.15
natural language processing    26.81
tensorflow                     21.57
image processing               16.54
pytorch                        16.23
deep learning                  15.50
data science                   15.29
chatbot                        14.55
algorithms                     13.19
generative ai                  11.83
sql                            10.37
ml                              9.32
data                            8.06
data analysis                   7.96
machine                         7.85
gcp                             7.75
aws                             7.54
kubernetes                      7.43
scikit-learn                    6.60
machine learning algorithms     6.49
aiml                            6.18
computer science                6.07
llm                             5.97
computer vision                 5.76
deep learning frameworks        5.13
c++                             4.92
statistics                      4.82
data analytics                  4.40
Name: count, dtype: float64

In [ ]:
ai_skills_normalized = (
    ai_ml_jobs["skills_clean"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

In [ ]:
ai_skills_normalized = ai_skills_normalized.replace({
    "ml": "machine learning",
    "machine learning algorithms": "machine learning",
    "nlp": "natural language processing",
    "gen ai": "generative ai",
    "aiml": "artificial intelligence"
})

In [ ]:
ai_skill_counts_clean = ai_skills_normalized.value_counts()

ai_skill_counts_clean.head(30)

skills_clean
machine learning               674
python                         543
artificial intelligence        366
natural language processing    281
tensorflow                     206
image processing               158
pytorch                        155
deep learning                  148
data science                   146
generative ai                  141
chatbot                        139
algorithms                     126
sql                             99
data                            77
data analysis                   76
machine                         75
gcp                             74
aws                             72
kubernetes                      71
scikit-learn                    63
computer science                58
llm                             57
computer vision                 55
deep learning frameworks        49
c++                             47
statistics                      46
data analytics                  42
microsoft azure                 40
langchain                       37
keras                           36
Name: count, dtype: int64

In [ ]:
ai_skill_percentage_clean = (
    ai_skill_counts_clean / len(ai_ml_jobs) * 100
).round(2)

ai_skill_percentage_clean.head(30)

skills_clean
machine learning               70.58
python                         56.86
artificial intelligence        38.32
natural language processing    29.42
tensorflow                     21.57
image processing               16.54
pytorch                        16.23
deep learning                  15.50
data science                   15.29
generative ai                  14.76
chatbot                        14.55
algorithms                     13.19
sql                            10.37
data                            8.06
data analysis                   7.96
machine                         7.85
gcp                             7.75
aws                             7.54
kubernetes                      7.43
scikit-learn                    6.60
computer science                6.07
llm                             5.97
computer vision                 5.76
deep learning frameworks        5.13
c++                             4.92
statistics                      4.82
data analytics                  4.40
microsoft azure                 4.19
langchain                       3.87
keras                           3.77
Name: count, dtype: float64

In [ ]:
ai_ml_jobs[
    ai_ml_jobs["skills_clean"].str.contains(
        r"(^|,)machine(,|$)",
        case=False,
        na=False
    )
][["title", "tagsAndSkills"]].head(20)

/tmp/ipykernel_4739/2278768926.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ai_ml_jobs["skills_clean"].str.contains(

,title,tagsAndSkills
1224,AI Engineer/ AI,"Aiml,Artificial Intelligence,Machine Learning,..."
1574,GenAI Data Scientist,"Gen AI,Python,NLP,LLM,Machine Learning,Gen,Dat..."
3366,Lead AI Engineer,"Artificial Intelligence,Al,LLM,Deep Learning,M..."
3669,Data Science and Machine Learning Engineer,"Data Science,Machine Learning,Python,Optimizat..."
6744,Artificial Intelligence Engineer,"Machine Learning,Artificial Intelligence,Gener..."
6745,Machine Learning Engineer,"Machine Learning,Artificial Intelligence,Gener..."
7806,Data Scientist,"Data Science,Generative AI,Aiml,Machine Learni..."
8723,GEN AI Developer,"Generative Ai,Machine Learning,Python,Gen,Arti..."
8816,AI Engineer (Financial Automation),"Tensorflow,Pytorch,Artificial Intelligence,Mac..."
9555,Data Scientist,"Ai Algorithms,Product Development,Generative A..."
10998,Data Scientist,"Data Science,Machine Learning,Python,Artificia..."
13496,AI Engineer,"Ai Algorithms,Aws Sagemaker,Machine Learning,P..."
14673,GenAI Developer,"Machine learning,Python,Machine,Development"
15624,Full-stack Data + ML Engineer (Mid-Level),"Python,SQL,Data Engineering,Kafka,LLM,Machine ..."
16856,Data Scientist,"Data Science,Python,Natural Language Processin..."
17407,Data Scientist,"Machine Learning,Deep Learning,Python,Tensorfl..."
17865,Senior Data Scientist,"Machine Learning,Predictive Analytics,Python,S..."
18024,Senior Data Scientist,"Artificial Intelligence,Natural Language Proce..."
18112,Lead Data Scientist / Machine Learning Enginee...,"Statistical Analyses,LLM,Machine Learning,Pyth..."
18612,Machine Learning Engineer (Azure + Databricks),"Pyspark,Azure Machine Learning,Data Bricks,Azu..."

In [ ]:
ai_ml_jobs[[
    "minSalary_clean",
    "maxSalary_clean"
]].describe()

       minSalary_clean  maxSalary_clean
count     1.350000e+02     1.350000e+02
mean      1.593111e+06     2.527037e+06
std       9.185586e+05     1.274764e+06
min       5.000000e+04     9.000000e+04
25%       1.000000e+06     1.700000e+06
50%       1.500000e+06     2.250000e+06
75%       2.000000e+06     3.500000e+06
max       4.000000e+06     7.000000e+06

In [ ]:
ai_ml_jobs["minimumExperience"].describe()

count    946.000000
mean       5.625793
std        3.838751
min        0.000000
25%        3.000000
50%        5.000000
75%        7.000000
max       20.000000
Name: minimumExperience, dtype: float64

In [ ]:
ai_ml_jobs["maximumExperience"].describe()

count    946.000000
mean       9.667019
std        4.572533
min        0.000000
25%        7.000000
50%        9.000000
75%       12.000000
max       30.000000
Name: maximumExperience, dtype: float64

**EXPLORATORY DATA ANALYSIS**

In [ ]:
df_clean["location"].value_counts().head(20)

location
Bengaluru                        16783
Hyderabad                         7657
Pune                              6096
Chennai                           4418
Gurugram                          4226
Mumbai                            4149
Noida                             2688
Remote                            1952
Ahmedabad                         1721
Navi Mumbai                       1451
Kolkata                           1047
Hyderabad, Chennai, Bengaluru     1037
Hybrid - Bengaluru                 944
Jaipur                             815
Coimbatore                         618
Hybrid - Hyderabad                 575
Kochi                              526
Vadodara                           526
Hybrid - Pune                      478
Thane                              408
Name: count, dtype: int64

In [ ]:
df_clean["title"].value_counts().head(20)

title
Application Developer             2033
Application Lead                  1346
Sales Executive                    576
Software Development Engineer      497
Business Development Executive     456
Trust & Safety New Associate       348
Data Engineer                      338
Business Development Manager       323
Sales Manager                      319
Java Full Stack Developer          282
Java Developer                     253
Relationship Manager               232
Area Sales Manager                 217
Application Support Engineer       217
Accountant                         215
Customer Support Executive         213
Senior Software Engineer           206
Account Executive                  205
Graphic Designer                   190
Software Development Lead          181
Name: count, dtype: int64

In [ ]:
df_clean["minimumExperience"].value_counts().sort_index()

minimumExperience
0.0     12363
1.0     15311
2.0     12793
3.0     13575
4.0      7474
5.0     12264
6.0      5268
7.0      4021
8.0      4484
9.0       914
10.0     3581
11.0      248
12.0     1403
13.0      285
14.0      210
15.0     2423
16.0      100
17.0       28
18.0      140
19.0       18
20.0      156
21.0       10
22.0        9
23.0        2
24.0        5
25.0       10
26.0        2
27.0        3
28.0        2
29.0        1
30.0        8
Name: count, dtype: int64

In [ ]:
df_clean["experience_level"] = pd.cut(
    df_clean["minimumExperience"],
    bins=[-1, 0, 2, 5, 10, 100],
    labels=["Fresher", "Junior", "Mid-level", "Senior", "Expert"]
)

df_clean["experience_level"].value_counts().sort_index()

experience_level
Fresher      12363
Junior       28104
Mid-level    33313
Senior       18268
Expert        5063
Name: count, dtype: int64

In [ ]:
salary_data = df_clean[
    df_clean["minSalary_clean"].notna() &
    df_clean["maxSalary_clean"].notna()
].copy()

In [ ]:
salary_data["experience_level"].value_counts().sort_index()

experience_level
Fresher       7422
Junior       11962
Mid-level     8380
Senior        4428
Expert         946
Name: count, dtype: int64

In [ ]:
salary_by_experience = (
    salary_data
    .groupby("experience_level", observed=True)[
        ["minSalary_clean", "maxSalary_clean"]
    ]
    .median()
)

salary_by_experience

                  minSalary_clean  maxSalary_clean
experience_level
Fresher                  200000.0         350000.0
Junior                   250000.0         450000.0
Mid-level                500000.0         800000.0
Senior                  1000000.0        1800000.0
Expert                  1800000.0        2875000.0

In [ ]:
ai_ml_salary = ai_ml_jobs[
    ai_ml_jobs["minSalary_clean"].notna() &
    ai_ml_jobs["maxSalary_clean"].notna()
].copy()

In [ ]:
ai_ml_salary["experience_level"] = pd.cut(
    ai_ml_salary["minimumExperience"],
    bins=[-1, 0, 2, 5, 10, 100],
    labels=["Fresher", "Junior", "Mid-level", "Senior", "Expert"]
)

In [ ]:
ai_ml_salary["experience_level"].value_counts().sort_index()

experience_level
Fresher       5
Junior       24
Mid-level    60
Senior       46
Expert        0
Name: count, dtype: int64

In [ ]:
ai_ml_jobs["location"].value_counts().head(20)

location
Bengaluru                                 248
Pune                                      113
Hyderabad                                  89
Chennai                                    56
Gurugram                                   50
Remote                                     42
Mumbai                                     26
Hybrid - Bengaluru                         22
Ahmedabad                                  21
Noida                                      12
Hybrid - Hyderabad                         11
Hyderabad, Chennai, Bengaluru              11
Hybrid - Pune                               9
Hybrid - Chennai                            7
Hybrid - Pune, Chennai, Bengaluru           7
Hybrid - Hyderabad, Chennai, Bengaluru      7
Kolkata                                     7
Mumbai, Delhi / NCR, Bengaluru              5
Vadodara                                    5
Chennai, Bengaluru                          5
Name: count, dtype: int64

In [ ]:
total_by_location = df_clean["location"].value_counts()

ai_ml_by_location = ai_ml_jobs["location"].value_counts()

location_analysis = pd.DataFrame({
    "total_jobs": total_by_location,
    "ai_ml_jobs": ai_ml_by_location
}).fillna(0)

In [ ]:
location_analysis["ai_ml_percentage"] = (
    location_analysis["ai_ml_jobs"] /
    location_analysis["total_jobs"] * 100
).round(2)

In [ ]:
location_analysis.sort_values(
    "ai_ml_percentage",
    ascending=False
).head(20)

,total_jobs,ai_ml_jobs,ai_ml_percentage
location,,,
Bengaluru(Hosur Road),1,1.0,100.00
"Hybrid - Noida, Pune, Gurugram, Bengaluru",1,1.0,100.00
"Noida, Hyderabad, New Delhi, Pune, Chennai, Bengaluru",1,1.0,100.00
"Hybrid - Gandhinagar, Chennai, Bengaluru",1,1.0,100.00
"Mumbai, Pune, Chennai, Gurugram, Coimbatore, Bengaluru",1,1.0,100.00
"Kolkata, Indore, Pune",1,1.0,100.00
"Chengalpattu, Chennai(Chengalpattu)",1,1.0,100.00
"Noida, Nagpur, Bengaluru",1,1.0,100.00
Hyderabad(Alwal +2),1,1.0,100.00
"Hybrid - Indore, Hyderabad, Bengaluru",1,1.0,100.00
"Tirodi, Mumbai",1,1.0,100.00
"Noida, Pune, Jaipur",1,1.0,100.00
"Hybrid - Mumbai, Kandivali East, Singh Agri Estate",1,1.0,100.00
"Hybrid - Chennai(SIDCO Industrial Estate, Guindy)",1,1.0,100.00
Chennai(OMR +1),1,1.0,100.00
"Visakhapatnam, Coimbatore",3,2.0,66.67
Bengaluru(Lavelle Road),2,1.0,50.00
"Noida, Indore",2,1.0,50.00
"Hybrid - Gandhinagar, Pune",2,1.0,50.00
"Hybrid - Mumbai, Gurugram, Chennai",2,1.0,50.00

In [ ]:
location_analysis_filtered = location_analysis[
    location_analysis["total_jobs"] >= 100
].copy()

In [ ]:
location_analysis_filtered.sort_values(
    "ai_ml_percentage",
    ascending=False
).head(20)

,total_jobs,ai_ml_jobs,ai_ml_percentage
location,,,
"Hybrid - Pune, Chennai, Bengaluru",125,7.0,5.60
Hybrid - Chennai,205,7.0,3.41
Gandhinagar,159,5.0,3.14
"Hybrid - Hyderabad, Chennai, Bengaluru",269,7.0,2.60
Hybrid - Bengaluru,944,22.0,2.33
Remote,1952,42.0,2.15
"Pune, Chennai, Bengaluru",147,3.0,2.04
"Hyderabad, Pune, Bengaluru",257,5.0,1.95
Hybrid - Hyderabad,575,11.0,1.91
Hybrid - Gurugram,159,3.0,1.89
Hybrid - Pune,478,9.0,1.88
"Pune, Bengaluru",160,3.0,1.88
Pune,6096,113.0,1.85
"Hyderabad, Bengaluru",279,5.0,1.79
"Chennai, Bengaluru",284,5.0,1.76
Bengaluru,16783,248.0,1.48
"Hybrid - Hyderabad, Pune, Bengaluru",213,3.0,1.41
Mohali,295,4.0,1.36
Chennai,4418,56.0,1.27
Ahmedabad,1721,21.0,1.22

In [ ]:
data_keywords = [
    "data analyst",
    "data scientist",
    "data engineer",
    "business analyst",
    "data analytics",
    "data science",
    "analytics engineer",
    "business intelligence"
]

pattern_data = "|".join(data_keywords)

data_jobs = df_clean[
    df_clean["title"].str.contains(
        pattern_data,
        case=False,
        na=False
    )
].copy()

In [ ]:
data_jobs.shape

(2432, 21)

In [ ]:
sde_keywords = [
    "software developer",
    "software engineer",
    "software development engineer",
    "application developer",
    "application engineer",
    "java developer",
    "python developer",
    "c++ developer",
    "frontend developer",
    "backend developer",
    "full stack developer",
    "web developer",
    "programmer",
    "devops engineer"
]

pattern_sde = "|".join(sde_keywords)

sde_jobs = df_clean[
    df_clean["title"].str.contains(
        pattern_sde,
        case=False,
        na=False
    )
].copy()

In [ ]:
sde_jobs.shape

(7440, 21)

In [ ]:
sde_skills = (
    sde_jobs["skills_clean"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

sde_skill_counts = sde_skills.value_counts()

sde_skill_counts.head(20)

skills_clean
css                          2163
java                         1661
python                       1415
application development      1113
c#                           1030
javascript                    997
rest                          955
spring boot                   914
sql                           872
sap                           862
microservices                 854
web services                  711
software development          682
development                   658
development methodologies     625
hibernate                     587
react.js                      544
continuous integration        518
html                          512
aws                           508
Name: count, dtype: int64

In [ ]:
data_skills = (
    data_jobs["skills_clean"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

data_skill_counts = data_skills.value_counts()

data_skill_counts.head(20)

skills_clean
python                1024
sql                    661
scala                  383
data                   378
pyspark                372
data analysis          355
hive                   317
data engineering       316
machine learning       304
business analysis      289
hadoop                 251
aws                    231
spark                  231
etl                    225
airflow                216
data modeling          199
data science           187
power bi               181
project management     180
gcp                    175
Name: count, dtype: int64

In [ ]:
def get_skill_counts(job_df):
    skills = (
        job_df["skills_clean"]
        .dropna()
        .str.split(",")
        .explode()
        .str.strip()
    )

    return skills.value_counts()

In [ ]:
sde_counts = get_skill_counts(sde_jobs)
data_counts = get_skill_counts(data_jobs)
ai_counts = ai_skills_normalized.value_counts()

In [ ]:
sde_counts.head(10)

skills_clean
css                        2163
java                       1661
python                     1415
application development    1113
c#                         1030
javascript                  997
rest                        955
spring boot                 914
sql                         872
sap                         862
Name: count, dtype: int64

In [ ]:
sde_skill_pct = (sde_counts / len(sde_jobs) * 100).round(2)

data_counts = get_skill_counts(data_jobs)
data_skill_pct = (data_counts / len(data_jobs) * 100).round(2)

In [ ]:
sde_skill_pct.head(15)

skills_clean
css                          29.07
java                         22.33
python                       19.02
application development      14.96
c#                           13.84
javascript                   13.40
rest                         12.84
spring boot                  12.28
sql                          11.72
sap                          11.59
microservices                11.48
web services                  9.56
software development          9.17
development                   8.84
development methodologies     8.40
Name: count, dtype: float64

In [ ]:
data_skill_pct.head(15)

skills_clean
python               42.11
sql                  27.18
scala                15.75
data                 15.54
pyspark              15.30
data analysis        14.60
hive                 13.03
data engineering     12.99
machine learning     12.50
business analysis    11.88
hadoop               10.32
aws                   9.50
spark                 9.50
etl                   9.25
airflow               8.88
Name: count, dtype: float64

In [ ]:
comparison = pd.DataFrame({
    "SDE": sde_skill_pct,
    "Data": data_skill_pct,
    "AI_ML": ai_counts / len(ai_ml_jobs) * 100
}).fillna(0)

In [ ]:
comparison.sort_values("AI_ML", ascending=False).head(30)

                               SDE   Data      AI_ML
skills_clean
machine learning              1.79  12.50  70.575916
python                       19.02  42.11  56.858639
artificial intelligence       1.16   3.82  38.324607
natural language processing   0.31   5.76  29.424084
tensorflow                    0.15   3.00  21.570681
image processing              0.05   0.37  16.544503
pytorch                       0.11   1.48  16.230366
deep learning                 0.07   2.96  15.497382
data science                  0.13   7.69  15.287958
generative ai                 0.19   1.85  14.764398
chatbot                       0.05   0.12  14.554974
algorithms                    2.33   2.71  13.193717
sql                          11.72  27.18  10.366492
data                          0.46  15.54   8.062827
data analysis                 1.02  14.60   7.958115
machine                       0.13   1.52   7.853403
gcp                           2.65   7.20   7.748691
aws                           6.83   9.50   7.539267
kubernetes                    6.44   1.36   7.434555
scikit-learn                  0.04   1.85   6.596859
computer science              3.75   4.19   6.073298
llm                           0.12   0.99   5.968586
computer vision               0.01   0.62   5.759162
deep learning frameworks      0.01   0.16   5.130890
c++                           6.30   0.90   4.921466
statistics                    0.24   1.23   4.816754
data analytics                0.65   6.41   4.397906
microsoft azure               2.74   4.52   4.188482
langchain                     0.07   0.37   3.874346
keras                         0.00   1.15   3.769634

In [ ]:
sde_salary = sde_jobs[
    sde_jobs["minSalary_clean"].notna() &
    sde_jobs["maxSalary_clean"].notna()
].copy()

data_salary = data_jobs[
    data_jobs["minSalary_clean"].notna() &
    data_jobs["maxSalary_clean"].notna()
].copy()

ai_ml_salary = ai_ml_jobs[
    ai_ml_jobs["minSalary_clean"].notna() &
    ai_ml_jobs["maxSalary_clean"].notna()
].copy()

In [ ]:
salary_comparison = pd.DataFrame({
    "SDE": [
        sde_salary["minSalary_clean"].median(),
        sde_salary["maxSalary_clean"].median()
    ],
    "Data": [
        data_salary["minSalary_clean"].median(),
        data_salary["maxSalary_clean"].median()
    ],
    "AI_ML": [
        ai_ml_salary["minSalary_clean"].median(),
        ai_ml_salary["maxSalary_clean"].median()
    ]
}, index=["Median Minimum Salary", "Median Maximum Salary"])

salary_comparison

                             SDE       Data      AI_ML
Median Minimum Salary  1000000.0  1500000.0  1500000.0
Median Maximum Salary  1800000.0  2100000.0  2250000.0

In [ ]:
pd.Series({
    "SDE": len(sde_salary),
    "Data": len(data_salary),
    "AI_ML": len(ai_ml_salary)
})

SDE      914
Data     552
AI_ML    135
dtype: int64

In [ ]:
for job_df in [sde_salary, data_salary, ai_ml_salary]:
    job_df["experience_level"] = pd.cut(
        job_df["minimumExperience"],
        bins=[-1, 0, 2, 5, 10, 100],
        labels=["Fresher", "Junior", "Mid-level", "Senior", "Expert"]
    )

In [ ]:
salary_by_career_experience = pd.DataFrame({
    "SDE": sde_salary.groupby(
        "experience_level", observed=True
    )["minSalary_clean"].median(),

    "Data": data_salary.groupby(
        "experience_level", observed=True
    )["minSalary_clean"].median(),

    "AI_ML": ai_ml_salary.groupby(
        "experience_level", observed=True
    )["minSalary_clean"].median()
})

salary_by_career_experience

                        SDE       Data      AI_ML
experience_level
Fresher            300000.0   462500.0   500000.0
Junior             300000.0   450000.0   800000.0
Mid-level          800000.0  1300000.0  1200000.0
Senior            1500000.0  1500000.0  2000000.0
Expert            2000000.0  1800000.0        NaN

In [ ]:
career_summary = pd.DataFrame({
    "Career": ["SDE", "Data", "AI/ML"],
    "Job_Count": [
        len(sde_jobs),
        len(data_jobs),
        len(ai_ml_jobs)
    ],
    "Median_Min_Salary": [
        sde_salary["minSalary_clean"].median(),
        data_salary["minSalary_clean"].median(),
        ai_ml_salary["minSalary_clean"].median()
    ],
    "Median_Max_Salary": [
        sde_salary["maxSalary_clean"].median(),
        data_salary["maxSalary_clean"].median(),
        ai_ml_salary["maxSalary_clean"].median()
    ]
})

career_summary

  Career  Job_Count  Median_Min_Salary  Median_Max_Salary
0    SDE       7440          1000000.0          1800000.0
1   Data       2432          1500000.0          2100000.0
2  AI/ML        955          1500000.0          2250000.0

In [ ]:
skill_comparison = (
    comparison
    .reset_index()
    .rename(columns={"skills_clean": "Skill"})
)

skill_comparison.head(20)

                               Skill   SDE  Data     AI_ML
0                               .net  2.89  0.04  0.314136
1                            .net 6+  0.03  0.00  0.000000
2                           .net api  0.03  0.00  0.000000
3         .net application developer  0.01  0.00  0.000000
4                  .net architecture  0.01  0.00  0.000000
5                            .net c#  0.01  0.00  0.000000
6                          .net core  1.84  0.00  0.000000
7                  .net core web api  0.03  0.00  0.000000
8                     .net developer  0.04  0.00  0.000000
9                      .net devloper  0.01  0.00  0.000000
10                    .net framework  0.09  0.00  0.000000
11                   .net frameworks  0.01  0.00  0.000000
12                   .net full stack  0.01  0.00  0.000000
13         .net full stack developer  0.01  0.00  0.000000
14                    .net fullstack  0.01  0.00  0.000000
15                          .net mvc  0.01  0.00  0.000000
16                     .net remoting  0.01  0.00  0.000000
17                       .net webapi  0.01  0.00  0.000000
18                          .netcore  0.04  0.00  0.000000
19  10+ years of experience in ai/ml  0.00  0.00  0.104712

In [ ]:
experience_salary = (
    salary_by_career_experience
    .reset_index()
    .rename(columns={"experience_level": "Experience_Level"})
)

experience_salary

  Experience_Level        SDE       Data      AI_ML
0          Fresher   300000.0   462500.0   500000.0
1           Junior   300000.0   450000.0   800000.0
2        Mid-level   800000.0  1300000.0  1200000.0
3           Senior  1500000.0  1500000.0  2000000.0
4           Expert  2000000.0  1800000.0        NaN

In [ ]:
top_skills = skill_comparison[
    (skill_comparison["SDE"] > 0) |
    (skill_comparison["Data"] > 0) |
    (skill_comparison["AI_ML"] > 0)
].copy()

top_skills = top_skills.sort_values(
    "AI_ML",
    ascending=False
).head(50)

top_skills

                            Skill    SDE   Data      AI_ML
3067             machine learning   1.79  12.50  70.575916
4152                       python  19.02  42.11  56.858639
472       artificial intelligence   1.16   3.82  38.324607
3470  natural language processing   0.31   5.76  29.424084
5396                   tensorflow   0.15   3.00  21.570681
2547             image processing   0.05   0.37  16.544503
4176                      pytorch   0.11   1.48  16.230366
1658                deep learning   0.07   2.96  15.497382
1568                 data science   0.13   7.69  15.287958
2295                generative ai   0.19   1.85  14.764398
1048                      chatbot   0.05   0.12  14.554974
248                    algorithms   2.33   2.71  13.193717
5088                          sql  11.72  27.18  10.366492
1481                         data   0.46  15.54   8.062827
1485                data analysis   1.02  14.60   7.958115
3064                      machine   0.13   1.52   7.853403
2266                          gcp   2.65   7.20   7.748691
599                           aws   6.83   9.50   7.539267
2898                   kubernetes   6.44   1.36   7.434555
4729                 scikit-learn   0.04   1.85   6.596859
1269             computer science   3.75   4.19   6.073298
3015                          llm   0.12   0.99   5.968586
1270              computer vision   0.01   0.62   5.759162
1659     deep learning frameworks   0.01   0.16   5.130890
952                           c++   6.30   0.90   4.921466
5158                   statistics   0.24   1.23   4.816754
1491               data analytics   0.65   6.41   4.397906
3260              microsoft azure   2.74   4.52   4.188482
2924                    langchain   0.07   0.37   3.874346
2873                        keras   0.00   1.15   3.769634
3517              neural networks   0.01   0.70   3.664921
2626                 intelligence   0.05   0.62   3.560209
1716                  development   8.84   0.82   3.455497
1551                 data munging   0.05   0.04   3.246073
164                    agentic ai   0.05   0.29   3.141361
576                    automation   3.32   3.33   3.141361
280                    analytical   1.57   5.10   3.141361
1316       continuous integration   6.96   1.69   2.931937
2440                         hive   0.65  13.03   2.931937
5284                      tableau   0.19   4.40   2.931937
3631                  open source   0.63   0.62   2.827225
1129                        cloud   1.96   1.81   2.827225
2282                          gen   0.03   0.29   2.617801
3375                   monitoring   0.62   1.32   2.513089
1581              data structures   2.49   0.90   2.513089
2311                          git   5.16   2.26   2.513089
4726                      science   0.00   1.40   2.303665
2746                         java  22.33   3.41   2.303665
286                     analytics   0.52   4.61   2.303665
1196                          cnn   0.00   0.16   2.198953

In [ ]:
sde_top10 = (
    skill_comparison[["Skill", "SDE"]]
    .sort_values("SDE", ascending=False)
    .head(10)
)

sde_top10

                        Skill    SDE
1419                      css  29.07
2746                     java  22.33
4152                   python  19.02
423   application development  14.96
947                        c#  13.84
2800               javascript  13.40
4376                     rest  12.84
5065              spring boot  12.28
5088                      sql  11.72
4579                      sap  11.59

In [ ]:
data_top10 = (
    skill_comparison[["Skill", "Data"]]
    .sort_values("Data", ascending=False)
    .head(10)
)

data_top10

                  Skill   Data
4152             python  42.11
5088                sql  27.18
4713              scala  15.75
1481               data  15.54
4149            pyspark  15.30
1485      data analysis  14.60
2440               hive  13.03
1512   data engineering  12.99
3067   machine learning  12.50
891   business analysis  11.88

In [ ]:
ai_top10 = (
    skill_comparison[["Skill", "AI_ML"]]
    .sort_values("AI_ML", ascending=False)
    .head(10)
)

ai_top10

                            Skill      AI_ML
3067             machine learning  70.575916
4152                       python  56.858639
472       artificial intelligence  38.324607
3470  natural language processing  29.424084
5396                   tensorflow  21.570681
2547             image processing  16.544503
4176                      pytorch  16.230366
1658                deep learning  15.497382
1568                 data science  15.287958
2295                generative ai  14.764398

In [ ]:
with pd.ExcelWriter("/content/job_market_analysis.xlsx") as writer:
    career_summary.to_excel(writer, sheet_name="Career Summary", index=False)
    experience_salary.to_excel(writer, sheet_name="Experience Salary", index=False)
    sde_top10.to_excel(writer, sheet_name="SDE Top 10", index=False)
    data_top10.to_excel(writer, sheet_name="Data Top 10", index=False)
    ai_top10.to_excel(writer, sheet_name="AI ML Top 10", index=False)

In [ ]:
import os

os.path.exists("/content/job_market_analysis.xlsx")

True

In [ ]:
location_career = pd.concat([
    sde_jobs.assign(Career="SDE"),
    data_jobs.assign(Career="Data"),
    ai_ml_jobs.assign(Career="AI/ML")
])

location_career_counts = (
    location_career
    .groupby(["Career", "location"])
    .size()
    .reset_index(name="Job_Count")
    .sort_values(["Career", "Job_Count"], ascending=[True, False])
)

location_career_counts.head(20)

    Career                                location  Job_Count
3    AI/ML                               Bengaluru        248
137  AI/ML                                    Pune        113
83   AI/ML                               Hyderabad         89
12   AI/ML                                 Chennai         56
24   AI/ML                                Gurugram         50
148  AI/ML                                  Remote         42
110  AI/ML                                  Mumbai         26
31   AI/ML                      Hybrid - Bengaluru         22
0    AI/ML                               Ahmedabad         21
124  AI/ML                                   Noida         12
46   AI/ML                      Hybrid - Hyderabad         11
89   AI/ML           Hyderabad, Chennai, Bengaluru         11
70   AI/ML                           Hybrid - Pune          9
36   AI/ML                        Hybrid - Chennai          7
51   AI/ML  Hybrid - Hyderabad, Chennai, Bengaluru          7
75   AI/ML       Hybrid - Pune, Chennai, Bengaluru          7
101  AI/ML                                 Kolkata          7
15   AI/ML                      Chennai, Bengaluru          5
20   AI/ML                             Gandhinagar          5
86   AI/ML                    Hyderabad, Bengaluru          5

In [ ]:
top_locations = (
    location_career_counts
    .groupby("Career")
    .head(10)
    .reset_index(drop=True)
)

top_locations

   Career            location  Job_Count
0   AI/ML           Bengaluru        248
1   AI/ML                Pune        113
2   AI/ML           Hyderabad         89
3   AI/ML             Chennai         56
4   AI/ML            Gurugram         50
5   AI/ML              Remote         42
6   AI/ML              Mumbai         26
7   AI/ML  Hybrid - Bengaluru         22
8   AI/ML           Ahmedabad         21
9   AI/ML               Noida         12
10   Data           Bengaluru        439
11   Data           Hyderabad        255
12   Data                Pune        200
13   Data             Chennai        134
14   Data            Gurugram        133
15   Data              Remote         76
16   Data              Mumbai         69
17   Data  Hybrid - Bengaluru         55
18   Data  Hybrid - Hyderabad         52
19   Data               Noida         46
20    SDE           Bengaluru       2391
21    SDE           Hyderabad        895
22    SDE                Pune        828
23    SDE             Chennai        388
24    SDE              Mumbai        267
25    SDE            Gurugram        209
26    SDE               Noida        170
27    SDE  Hybrid - Bengaluru        162
28    SDE              Remote        147
29    SDE         Navi Mumbai        111

In [ ]:
with pd.ExcelWriter(
    "/content/job_market_analysis.xlsx",
    mode="a",
    engine="openpyxl"
) as writer:
    top_locations.to_excel(
        writer,
        sheet_name="Top Locations",
        index=False
    )

In [ ]:
pd.ExcelFile("/content/job_market_analysis.xlsx").sheet_names

['Career Summary',
 'Experience Salary',
 'SDE Top 10',
 'Data Top 10',
 'AI ML Top 10',
 'Top Locations']

In [ ]:
from google.colab import files

files.download("/content/job_market_analysis.xlsx")

In [ ]:
experience_distribution = pd.concat([
    sde_jobs.assign(Career="SDE"),
    data_jobs.assign(Career="Data"),
    ai_ml_jobs.assign(Career="AI/ML")
])

experience_distribution = (
    experience_distribution
    .groupby(["Career", "experience_level"])
    .size()
    .reset_index(name="Job_Count")
)

experience_distribution

/tmp/ipykernel_4739/3955807778.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["Career", "experience_level"])

   Career experience_level  Job_Count
0   AI/ML          Fresher          0
1   AI/ML           Junior          0
2   AI/ML        Mid-level          0
3   AI/ML           Senior          0
4   AI/ML           Expert          0
5    Data          Fresher         61
6    Data           Junior        361
7    Data        Mid-level       1146
8    Data           Senior        787
9    Data           Expert         64
10    SDE          Fresher        119
11    SDE           Junior       1405
12    SDE        Mid-level       3771
13    SDE           Senior       1400
14    SDE           Expert        720

In [ ]:
experience_distribution.to_excel(
    writer,
    sheet_name="Experience Distribution",
    index=False
)

In [ ]:
with pd.ExcelWriter(
    "/content/job_market_analysis.xlsx",
    mode="a",
    engine="openpyxl",
    if_sheet_exists="replace"
) as writer:

    experience_distribution.to_excel(
        writer,
        sheet_name="Experience Distribution",
        index=False
    )

In [ ]:
pd.ExcelFile("/content/job_market_analysis.xlsx").sheet_names

['Career Summary',
 'Experience Salary',
 'SDE Top 10',
 'Data Top 10',
 'AI ML Top 10',
 'Top Locations',
 'Experience Distribution']

In [ ]:
import os

print(os.path.exists("/content/job_market_analysis.xlsx"))

True

In [ ]:
print(pd.ExcelFile("/content/job_market_analysis.xlsx").sheet_names)

['Career Summary', 'Experience Salary', 'SDE Top 10', 'Data Top 10', 'AI ML Top 10', 'Top Locations', 'Experience Distribution']

In [ ]:
from google.colab import files

files.download("/content/job_market_analysis.xlsx")

In [ ]:
work_type_data = pd.concat([
    sde_jobs.assign(Career="SDE"),
    data_jobs.assign(Career="Data"),
    ai_ml_jobs.assign(Career="AI/ML")
])

work_type_data["Work_Type"] = work_type_data["location"].apply(
    lambda x: "Remote" if "remote" in str(x).lower()
    else "Hybrid" if "hybrid" in str(x).lower()
    else "On-site"
)

work_type_summary = (
    work_type_data
    .groupby(["Career", "Work_Type"])
    .size()
    .reset_index(name="Job_Count")
)

work_type_summary

  Career Work_Type  Job_Count
0  AI/ML    Hybrid        130
1  AI/ML   On-site        783
2  AI/ML    Remote         42
3   Data    Hybrid        550
4   Data   On-site       1806
5   Data    Remote         76
6    SDE    Hybrid        832
7    SDE   On-site       6461
8    SDE    Remote        147

In [ ]:
with pd.ExcelWriter(
    "/content/job_market_analysis.xlsx",
    mode="a",
    engine="openpyxl",
    if_sheet_exists="replace"
) as writer:

    work_type_summary.to_excel(
        writer,
        sheet_name="Work Type",
        index=False
    )

In [ ]:
from google.colab import files

files.download("/content/job_market_analysis.xlsx")